[package]
name = "fx3-tools-rs"
version = "0.1.0"
authors = ["Mary"]
license = "Apache-2.0 OR MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.8.0"
structopt = "0.3"
nom = "6.1.2"
